project/book/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path('', views.get_info, name='get_info'),
    path('books/<int:pk>/', views.get_book, name='get_book'),
    path('book/<int:pk>/', views.detail, name='detail'),
    path('add/', views.add_book, name='add_book'),
    path('update/<int:pk>/', views.update_book, name='update_book'),
    path('delete/<int:pk>/', views.delete_book, name='delete_book'),
    
]

project/project/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    year = models.IntegerField()

    class Meta:
        db_table = 'author'

    def __str__(self) -> str:
        return self.name

class category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'category'

    def __str__(self) -> str:
        return self.name

class Book(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    price = models.IntegerField()
    image = models.ImageField(upload_to='media/', blank=True, null=True)
    year = models.IntegerField()
    book_category = models.ForeignKey(category, on_delete=models.CASCADE)

    class Meta:
        db_table = 'book'

    def __str__(self) -> str:
        return self.name


class BookAuthor(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    class Meta:
        db_table = 'book_author'

    def __str__(self) -> str:
        return self.author.name

class Review(models.Model):
    comment = models.CharField(max_length=100)
    star_given = models.IntegerField()
    user = models.CharField(max_length=100)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    class Meta:
        db_table = 'review'

    def __str__(self) -> str:
        return self.comment

project/project/forms.py
from django.forms import ModelForm
from .models import Book

class ProductForm(ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

project/project/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Author, Book, category, BookAuthor, Review
from .forms import ProductForm

def get_info(request):      
    Category = category.objects.all()
    context = {
        'Category': Category,
    }
    return render(request, 'index.html', context=context)



from django.shortcuts import render
from .models import Book

def get_book(request, pk):
    books = Book.objects.all()
    context = {
        'books': books,
    }
    return render(request, 'books.html', context=context)

def detail(request, pk):
    book = Book.objects.get(pk=pk)
    context = {
        'Book': book,
    }
    return render(request, 'detail.html', context=context)

def add_book(request):
    form = ProductForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('project:get_info')
    context = {
        'form': form
    }
    return render(request, 'create.html',context=context)

def update_book(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect('project:get_info') 
    else:
        form = ProductForm(instance=book)

    context = {'form': form}
    return render(request, 'update.html', context)

def delete_book(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        book.delete()
        return redirect('project:get_info')
    return render(request, 'delete.html', {'book':book})

project/project/templates/books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Books</title>
</head>
<body>

<h1>Books</h1><br>


<body>
    {% for p in books %}

        <a class="link" href="{% url 'project:detail' p.pk %}" >{{ p.name }}</a><hr>

    {% endfor %}
<style>
    .link{
        color: black;
    }
</style>
</body>
</body>
</html>

project/project/templates/create.html
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Save</button>
</form>

project/project/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Product</title>
</head>
<body>

    <h1>Delete Product</h1>
    <p>Are you sure you want to delete the product "{{ product.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm Delete</button>
    </form>
    <a href="{% url 'project:get_info' %}">Cancel</a>

</body>
</html>

project/project/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>

<img src="{{ Book.image.url }}"/><br>
Name: {{ Book.name }}<br>
Description: {{ Book.description }}<br>
Price: {{ Book.price }}<br>
Year: {{ Book.year }}<br>
Category: {{ Book.book_category }}<hr/>

<a href="{% url 'project:get_info' %}" >Home</a><br>
<a href="{% url 'project:update_book' Book.pk %}" >Update</a><br>
<a href="{% url 'project:delete_book' Book.pk %}" >Delete</a><br>

</body>
</html>

project/project/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <!-- <link rel="stylesheet" href="style.css"> -->
</head>
<body>
   <style>
    @import url("https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap");

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  display: grid;
  align-items: center;
  justify-content: center;
  height: 100vh;
  background-color: #f2f2f2;
  font-family: "Roboto", sans-serif;
}

.wrap1 {
  text-align: center;
}

.header-heading {
  color: rgb(64, 248, 23);
  font-size: 36px;
  margin-bottom: 20px;
}

.header-context {
  font-size: 24px;
  margin-bottom: 30px;
}

.header-wrap {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 20px;
}

.c-btn {
  font-weight: 700;
  font-size: 14px;
  line-height: 17px;
  color: #ffffff;
  background-color: #1f4aa8;
  border-radius: 39px;
  text-decoration: none;
}

.header-category {
  text-decoration: none;
  color: #ffffff;
}
a{
  text-decoration: none;
  color: #ffffff;
}
.header-btn {
  font-weight: 700;
  font-size: 14px;
  line-height: 17px;
  color: #ffffff;
  background-color: #1fa848;
  border-radius: 39px;
  text-decoration: none;
}

.c-btn:hover,
.header-btn:hover {
  opacity: 0.9;
  cursor: pointer;
}

.c-btn:active,
.header-btn:active {
  transform: scale(0.95);
}
.header-link{
  padding: 50px;
}
.wrap3{
  display: grid;
  align-items: center;
  justify-content: center;
  gap: 20px;
  grid-column: 1;
}
.wrap2{
  /* margin-top: -120%;
margin-left: 190px; */
}
</style>
    <div class="wrap1">
      <h1 class="header-heading">Home page</h1>
    </div>
    <div class="wrap3">
          <h3 class="header-context">Categories</h3>
          {% for c in Category %}
          <button class="c-btn">
            <a class=" header-link" href="{% url 'project:get_book' c.pk %}" >{{ c.name }}</a><br>
          </button>
          {% endfor %}
        </div>
        
        <div class="wrap2">
          <button class="header-btn">
              <a class="header-link" href="{% url 'project:add_book' %}" >Add Books</a><br>
          </button>
        </div>

 

</body>
</html>

project/project/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Book</title>
</head>
<body>
    <h1>Update Book</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Book</button>
    </form>
</body>
</html>